// Tipos e registo dos passos do tutorial guiado do dashboard admin.
import type { AdminView } from '@/components/admin/dashboard-types';

export interface TourStep {
  id: string;
  view: AdminView;
  targetSelector: string;
  title: string;
  body: string;
  placement?: 'top' | 'bottom' | 'left' | 'right';
  order: number;
  /** Selector (ex: data-tour de um TabsTrigger) clicado antes de resolver
   * targetSelector — usado por áreas com tabs internas, para o passo abrir
   * a tab certa antes de apontar para o elemento. */
  activateSelector?: string;
}

export interface TourArea {
  view: AdminView;
  label: string;
  steps: TourStep[];
}

export const TOUR_AREAS: TourArea[] = [
  {
    view: 'overview',
    label: 'Visão geral',
    steps: [
      {
        id: 'overview-banner',
        view: 'overview',
        targetSelector: '[data-tour="overview-banner"]',
        title: 'Informações do portal',
        body: 'Data e hora ao vivo, mais mensagens sobre o estado do portal em rotação — sempre visível no topo.',
        placement: 'bottom',
        order: 1,
      },
      {
        id: 'overview-stats',
        view: 'overview',
        targetSelector: '[data-tour="overview-stats"]',
        title: 'Os teus números',
        body: 'Publicações do mês, total, visualizações e rascunhos — o resumo rápido do portal.',
        placement: 'bottom',
        order: 2,
      },
      {
        id: 'overview-articles',
        view: 'overview',
        targetSelector: '[data-tour="overview-articles"]',
        title: 'Últimos artigos',
        body: 'A tua atividade editorial recente. Clica num artigo para o abrir e editar.',
        placement: 'right',
        order: 3,
      },
      {
        id: 'overview-nav',
        view: 'overview',
        targetSelector: '[data-tour="nav-content"]',
        title: 'Navegação',
        body: 'Usa o menu lateral para mudar de área — Conteúdo, Automações, Configurações e mais.',
        placement: 'right',
        order: 4,
      },
    ],
  },
  {
    view: 'content',
    label: 'Conteúdo',
    steps: [
      {
        id: 'content-new-post',
        view: 'content',
        targetSelector: '[data-tour="content-new-post"]',
        title: 'Criar um post',
        body: 'Começa aqui um novo artigo editorial — abre o editor completo.',
        placement: 'bottom',
        order: 1,
      },
      {
        id: 'content-search',
        view: 'content',
        targetSelector: '[data-tour="content-search"]',
        title: 'Procurar posts',
        body: 'A pesquisa por título ou categoria fica sempre no topo, aqui — muda consoante a área onde estás.',
        placement: 'bottom',
        order: 2,
      },
      {
        id: 'content-filter',
        view: 'content',
        targetSelector: '[data-tour="content-filter"]',
        title: 'Filtrar por estado',
        body: 'Alterna entre todos os posts, só publicados ou só rascunhos.',
        placement: 'bottom',
        order: 3,
      },
      {
        id: 'content-tabs',
        view: 'content',
        targetSelector: '[data-tour="content-tabs"]',
        title: 'Posts, curadoria e categorias',
        body: 'Alterna entre posts editoriais, sugestões curadas pela IA e gestão de categorias.',
        placement: 'top',
        order: 4,
      },
    ],
  },
  {
    view: 'media',
    label: 'Media',
    steps: [
      {
        id: 'media-upload',
        view: 'media',
        targetSelector: '[data-tour="media-upload"]',
        title: 'Carregar imagens',
        body: 'Envia uma ou várias imagens (JPG, PNG, WebP ou GIF, até 5MB cada) para a galeria — ficam disponíveis para usar em qualquer artigo.',
        placement: 'bottom',
        order: 1,
      },
      {
        id: 'media-grid',
        view: 'media',
        targetSelector: '[data-tour="media-grid"]',
        title: 'Galeria',
        body: 'Passa o rato sobre uma imagem para copiar o link público (usa-o no editor de posts) ou eliminar a imagem da galeria.',
        placement: 'top',
        order: 2,
      },
    ],
  },
  {
    view: 'automations',
    label: 'Automações',
    steps: [
      {
        id: 'automation-engine-status',
        view: 'automations',
        targetSelector: '[data-tour="automation-engine-status"]',
        title: 'Estado do motor',
        body: 'WF-01, WF-02 e WF-03 são os três workflows n8n que movem o pipeline editorial. Os pontos aqui mostram se cada um está ativo e a comunicar bem com o portal — se um ficar vermelho, é sinal de que essa etapa parou.',
        placement: 'bottom',
        order: 1,
      },
      {
        id: 'automation-stages',
        view: 'automations',
        targetSelector: '[data-tour="automation-stages"]',
        title: 'Como funciona o pipeline',
        body: 'Coleta (WF-01) traz notícias de fontes externas para staging. Cluster (WF-02) agrupa notícias semelhantes e decide o que vale a pena aprofundar. IA Reescrita (WF-03) usa o motor de IA para escrever, rever e publicar o artigo. Publicação é o artigo já visível no portal. Cada número mostra quantos itens estão nessa etapa agora.',
        placement: 'bottom',
        order: 2,
      },
      {
        id: 'automation-queue',
        view: 'automations',
        targetSelector: '[data-tour="automation-queue"]',
        title: 'Fila de conteúdo',
        body: 'Os mesmos artigos, agora agrupados por estado — útil para veres rapidamente o que está parado ou por rever, sem teres de percorrer o pipeline inteiro.',
        placement: 'top',
        order: 3,
      },
      {
        id: 'automation-review',
        view: 'automations',
        targetSelector: '[data-tour="automation-review"]',
        title: 'Revisão detalhada',
        body: 'Aqui vês os artigos que a IA já preparou, antes de saírem para o portal — podes rever, editar ou promover cada um individualmente.',
        placement: 'top',
        order: 4,
      },
      {
        id: 'automation-cleanup',
        view: 'automations',
        targetSelector: '[data-tour="automation-cleanup"]',
        title: 'Limpeza do pipeline',
        body: 'Remove notícias em staging já processadas, clusters órfãos e curados já publicados/rejeitados mais antigos que o prazo escolhido. Rascunhos e conteúdo pronto a publicar nunca são apagados — só o que já não serve para nada.',
        placement: 'top',
        order: 5,
      },
      {
        id: 'automation-tab-automations',
        view: 'automations',
        targetSelector: '[data-tour="automation-list-toolbar"]',
        activateSelector: '[data-tour="automation-tab-automations"]',
        title: 'Automações personalizadas',
        body: 'Além do pipeline de notícias, podes criar as tuas próprias automações — agendadas ou disparadas por evento — organizadas por categoria: pipeline de conteúdo, campanhas de email, auditoria/segurança, processos internos e integrações.',
        placement: 'bottom',
        order: 6,
      },
      {
        id: 'automation-tab-logs',
        view: 'automations',
        targetSelector: '[data-tour="automation-logs-executions"]',
        activateSelector: '[data-tour="automation-tab-logs"]',
        title: 'Histórico de execuções',
        body: 'Todas as execuções do pipeline e das automações, com sucesso, erro ou a decorrer. É o primeiro sítio a olhar quando algo parece não estar a correr.',
        placement: 'bottom',
        order: 7,
      },
      {
        id: 'automation-tab-tools',
        view: 'automations',
        targetSelector: '[data-tour="automation-tools-workflows"]',
        activateSelector: '[data-tour="automation-tab-tools"]',
        title: 'Workflows n8n e ferramentas',
        body: 'A lista real dos workflows configurados no n8n (o motor de automação por trás do pipeline), e ferramentas de apoio como o envio de templates de email para teste.',
        placement: 'bottom',
        order: 8,
      },
    ],
  },
  {
    view: 'courses',
    label: 'Cursos e parceiros',
    steps: [
      {
        id: 'courses-form',
        view: 'courses',
        targetSelector: '[data-tour="courses-form"]',
        title: 'Cursos, produtos e parcerias',
        body: 'Cria cartões de curso, produto, serviço ou link de afiliado — cada tipo mostra campos diferentes (ex: nível e duração só aparecem para cursos).',
        placement: 'right',
        order: 1,
      },
      {
        id: 'courses-catalog',
        view: 'courses',
        targetSelector: '[data-tour="courses-catalog"]',
        title: 'Catálogo actual',
        body: 'Tudo o que já está publicado na vitrine de cursos/parceiros do portal. Edita ou remove qualquer item daqui.',
        placement: 'left',
        order: 2,
      },
    ],
  },
  {
    view: 'crm',
    label: 'CRM',
    steps: [
      {
        id: 'crm-contacts',
        view: 'crm',
        targetSelector: '[data-tour="crm-content-contacts"]',
        activateSelector: '[data-tour="crm-tab-contacts"]',
        title: 'Contactos',
        body: 'Base de contactos e leads do portal — pesquisa por email/nome/empresa, filtra por tipo, exporta em CSV ou adiciona um novo contacto manualmente.',
        placement: 'bottom',
        order: 1,
      },
      {
        id: 'crm-newsletter',
        view: 'crm',
        targetSelector: '[data-tour="crm-content-newsletter"]',
        activateSelector: '[data-tour="crm-tab-newsletter"]',
        title: 'Newsletter',
        body: 'Envia uma newsletter para todos os subscritores ativos, e gere a lista de subscritores (ativar/desativar, remover).',
        placement: 'bottom',
        order: 2,
      },
      {
        id: 'crm-deals',
        view: 'crm',
        targetSelector: '[data-tour="crm-content-deals"]',
        activateSelector: '[data-tour="crm-tab-deals"]',
        title: 'Pipeline de parcerias',
        body: 'Quadro estilo Kanban para acompanhar negociações de parcerias/afiliados — arrasta ou muda a fase de cada negócio à medida que avança.',
        placement: 'bottom',
        order: 3,
      },
    ],
  },
  {
    view: 'analytics',
    label: 'Analytics',
    steps: [
      {
        id: 'analytics-period',
        view: 'analytics',
        targetSelector: '[data-tour="analytics-period"]',
        title: 'Período',
        body: 'Muda entre 7, 30 ou 90 dias — todos os números e gráficos abaixo actualizam-se de acordo com esta escolha.',
        placement: 'bottom',
        order: 1,
      },
      {
        id: 'analytics-kpis',
        view: 'analytics',
        targetSelector: '[data-tour="analytics-kpis"]',
        title: 'Números-chave',
        body: 'Total de eventos, dias com actividade, média diária e tendência (comparação da segunda metade do período com a primeira).',
        placement: 'bottom',
        order: 2,
      },
      {
        id: 'analytics-charts',
        view: 'analytics',
        targetSelector: '[data-tour="analytics-charts"]',
        title: 'Gráficos',
        body: 'Eventos diários ao longo do tempo, e a distribuição por tipo de evento — para perceberes não só quanto, mas o quê está a gerar mais actividade.',
        placement: 'top',
        order: 3,
      },
    ],
  },
  {
    view: 'access',
    label: 'Acesso',
    steps: [
      {
        id: 'access-mfa',
        view: 'access',
        targetSelector: '[data-tour="access-mfa"]',
        title: 'Segurança da tua conta',
        body: 'Ativa a autenticação de dois fatores (TOTP) na tua própria conta — recomendado para qualquer perfil de administração.',
        placement: 'bottom',
        order: 1,
      },
      {
        id: 'access-invite',
        view: 'access',
        targetSelector: '[data-tour="access-invite"]',
        title: 'Convidar um novo membro',
        body: 'Envia um convite por email já com o papel definido. O convite tem prazo de validade e só pode ser usado uma vez.',
        placement: 'right',
        order: 2,
      },
      {
        id: 'access-team',
        view: 'access',
        targetSelector: '[data-tour="access-content-team"]',
        activateSelector: '[data-tour="access-tab-team"]',
        title: 'Equipa',
        body: 'Todos os membros com acesso ao dashboard. Importante: só um super_admin pode mudar o papel de alguém ou desativar/reativar um membro — e ninguém pode alterar a sua própria conta por aqui.',
        placement: 'left',
        order: 3,
      },
      {
        id: 'access-invites',
        view: 'access',
        targetSelector: '[data-tour="access-content-invites"]',
        activateSelector: '[data-tour="access-tab-invites"]',
        title: 'Convites pendentes',
        body: 'Convites ainda por aceitar — podes reenviar ou expirar manualmente um convite antes do prazo.',
        placement: 'left',
        order: 4,
      },
      {
        id: 'access-roles',
        view: 'access',
        targetSelector: '[data-tour="access-content-roles"]',
        activateSelector: '[data-tour="access-tab-roles"]',
        title: 'Papéis disponíveis',
        body: 'Consulta (só leitura) o que cada papel — super_admin, admin, editor, redator, moderador, analyst — pode fazer no dashboard.',
        placement: 'left',
        order: 5,
      },
    ],
  },
  {
    view: 'developer',
    label: 'Developer',
    steps: [
      {
        id: 'developer-diagnostics',
        view: 'developer',
        targetSelector: '[data-tour="developer-content-diagnostics"]',
        activateSelector: '[data-tour="developer-tab-diagnostics"]',
        title: 'Diagnósticos',
        body: 'Saúde técnica do portal — ligação à base de dados, sessão autenticada, conectividade — mais notas técnicas internas e um ranking dos posts mais vistos.',
        placement: 'bottom',
        order: 1,
      },
      {
        id: 'developer-vault',
        view: 'developer',
        targetSelector: '[data-tour="developer-content-vault"]',
        activateSelector: '[data-tour="developer-tab-vault"]',
        title: 'Credential Vault',
        body: 'Guarda aqui chaves e segredos usados em integrações (API keys, SMTP, OAuth2, webhooks). São dados sensíveis — os valores ficam ocultos por padrão, e recebes aviso quando uma credencial está perto de expirar.',
        placement: 'bottom',
        order: 2,
      },
    ],
  },
  {
    view: 'settings',
    label: 'Configurações',
    steps: [
      {
        id: 'settings-site',
        view: 'settings',
        targetSelector: '[data-tour="settings-site"]',
        title: 'Identidade do portal',
        body: 'Nome, logótipo e definições gerais do site.',
        placement: 'bottom',
        order: 1,
      },
      {
        id: 'settings-ai',
        view: 'settings',
        targetSelector: '[data-tour="settings-ai"]',
        title: 'Assistente IA',
        body: 'Ativa e configura o assistente de IA do portal — modelo e comportamento.',
        placement: 'bottom',
        order: 2,
      },
      {
        id: 'settings-tutorial',
        view: 'settings',
        targetSelector: '[data-tour="settings-tutorial"]',
        title: 'Controlo do tutorial',
        body: 'Aqui podes desligar o tutorial a qualquer momento, ver o progresso ou reiniciá-lo.',
        placement: 'bottom',
        order: 3,
      },
    ],
  },
];
